In [77]:
import torch
print(torch.__version__)

2.1.1


In [78]:
# What does this torch.tensor() return?
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
tensor

# Constant 1-D Tensor populated with value list

tensor([1, 2, 3, 4, 5, 6])

In [79]:
# What is the shape of the resulting tensor?
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
tensor.shape

# Size object

torch.Size([6])

In [80]:
# What is the content of the resulting Tensor?
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
tensor = torch.reshape(tensor, (2, 3))
tensor
# A 2x3 matrix (two rows = the first dim, three
# columns = the second dim)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [81]:
# What is the content of the resulting Tensor?
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
tensor = torch.reshape(tensor, (3, 2))
tensor
# A 3x2 matrix (three rows = the first dim,
# two columns = the second dim)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [82]:
# What is the content of the resulting Tensor?
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
tensor = torch.reshape(tensor, shape=(3, 2, 1))
tensor
# 3-D Tensor

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

In [83]:
# What is the content of the resulting Tensor?
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
tensor = torch.reshape(tensor, shape=(3, 1, 2))
tensor
# 3-D Tensor with the second dimension kind of superfluous

tensor([[[1, 2]],

        [[3, 4]],

        [[5, 6]]])

In [84]:
# What is the output of torch.fill()?
tensor = torch.full([2, 3], 9)
tensor
# A 2-rows 3-columns tensor populated with 9 as int

tensor([[9, 9, 9],
        [9, 9, 9]])

In [85]:
# What is the output and shape of this code?
x = torch.tensor([1, 4])
y = torch.tensor([2, 5])
z = torch.tensor([3, 6])
torch.stack([x, y, z])
# (3,2) tensor stacked along the first dimension

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [86]:
# What is the output and shape of this code?
x = torch.tensor([1, 4])
y = torch.tensor([2, 5])
z = torch.tensor([3, 6])
torch.stack([x, y, z], dim=1)
# (2,3) tensor stacked along the second dimension

tensor([[1, 2, 3],
        [4, 5, 6]])

In [87]:
# What does this code produce and why?
c = torch.tensor([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0]])
c.shape
# A Size object with a list of Dimension objects
# 2 and 3

torch.Size([2, 3])

In [88]:
# What does this code produce and why?
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
tensor[2:-2]
# Strip leading and trailing 2 elements

tensor([3, 4])

In [89]:
# What does this code produce and why?
tensor = torch.tensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9],
                       [10, 11, 12]])
tensor[::2,]
# Skip every other row and reverse the order
# of the columns

tensor([[1, 2, 3],
        [7, 8, 9]])

In [90]:
# What does this code produce and why?
tensor = torch.tensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
tensor[torch.tensor(0), torch.tensor(2)]

# The value at coordinates 0,2 as a scalar tensor

tensor(3)

In [91]:
# What does this code produce and why?
tensor = torch.tensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
tensor[torch.tensor(0)]

# A cut on position 0 in the first dimension;
# the first row

tensor([1, 2, 3])

In [92]:
# What does this code produce and why?
tensor = torch.tensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
tensor[:, torch.tensor(0)]

# A cut on position 0 in the second dimension;
# the first column


tensor([1, 4, 7])

In [93]:
# What are other two equivalent operations to selecting
# the first row:
tensor = torch.tensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
tensor[torch.tensor(0)]

# With explicit ellipses for other dimensions
tensor[torch.tensor(0), :]
# With ellipsis
tensor[torch.tensor(0), ...]

tensor([1, 2, 3])

## Broadcasting

In [94]:
# Broadcasting in torch: what is the output?
a = torch.tensor(3)
b = torch.tensor(4)
a + b

# Simple scalar: 7

tensor(7)

In [95]:
# Broadcasting in torch: what is the output and why?
a = torch.tensor([1, 2])
b = torch.tensor(4)
a + b

# b is broadcast to all items in a

tensor([5, 6])

In [96]:
# Broadcasting in torch: what is the output and why?
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
a + b

# Element-wise operation

tensor([5, 7, 9])

In [97]:
# Broadcasting in torch: what is the output and why?
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
a + b

# Elementwise addition

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [98]:
# Broadcasting in torch: what is the output and why?
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([10, 20, 30])
a + b

# b is broadcast along each row in a

tensor([[11, 22, 33],
        [14, 25, 36]])

In [99]:
# Broadcasting in torch: what is the output and why?
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[1], [2]])
a + b

# b is broadcast along each column in a

tensor([[2, 3, 4],
        [6, 7, 8]])

In [100]:
# Broadcasting in torch: what is the output and why?
a = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ], [
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]
    ]])
b = torch.tensor([10, 20, 30])
a + b

# b is broadcast along the inner-most dimension in a

tensor([[[11, 22, 33],
         [14, 25, 36],
         [17, 28, 39]],

        [[21, 32, 43],
         [24, 35, 46],
         [27, 38, 49]]])

In [101]:
# Broadcasting in torch: what is the output and why?
a = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ], [
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]
    ]])
b = torch.tensor([[10], [20], [30]])
a + b

# b is broadcast along the second dimension in a

tensor([[[11, 12, 13],
         [24, 25, 26],
         [37, 38, 39]],

        [[21, 22, 23],
         [34, 35, 36],
         [47, 48, 49]]])

In [102]:
# Broadcasting in torch: what is the output and why?
a = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ], [
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]
    ]])
b = torch.tensor([[[10]], [[20]]])
a + b

# b is broadcast along the first dimension in a

tensor([[[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]],

        [[31, 32, 33],
         [34, 35, 36],
         [37, 38, 39]]])

In [103]:
# Broadcasting in torch: what is the output and why?
a = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ], [
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]
    ]])
b = torch.tensor([10, 20, 30])
a * b

# b is broadcast along the inner-most dimension in a

tensor([[[ 10,  40,  90],
         [ 40, 100, 180],
         [ 70, 160, 270]],

        [[110, 240, 390],
         [140, 300, 480],
         [170, 360, 570]]])

In [104]:
# Broadcasting in torch: what is the output and why?
a = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ], [
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]
    ]])
b = torch.tensor([[10], [20], [30]])
a * b

# b is broadcast along the second dimension in a

tensor([[[ 10,  20,  30],
         [ 80, 100, 120],
         [210, 240, 270]],

        [[110, 120, 130],
         [280, 300, 320],
         [510, 540, 570]]])

In [105]:
# Broadcasting in torch: what is the output and why?
a = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ], [
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]
    ]])
b = torch.tensor([[10], [20], [30]])
torch.matmul(a, b)

# a is multiplied by a "column-vector" b twice

tensor([[[ 140],
         [ 320],
         [ 500]],

        [[ 740],
         [ 920],
         [1100]]])

In [106]:
# Broadcasting in torch: what is the output and why?
a = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ], [
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]
    ]])
b = torch.full((3, 1), 10)

torch.matmul(a, b)

# a is multiplied by a "column-vector" b twice

tensor([[[ 60],
         [150],
         [240]],

        [[360],
         [450],
         [540]]])

In [107]:
# Which operator (for Python 3.5+) is for matrix multiplication
# and is implemented in torch?
a = torch.tensor([
                    [1, 2]
                ])
b = torch.tensor([
                    [3],
                    [4]
                ])

# at-sign
a @ b

tensor([[11]])

In [108]:
# What is the result and why?
t = torch.tensor([[1, 5, 3],
                 [4, 2, 6]])
torch.max(t)

# If no dimension provided, reduces to a scalar
# among all dimensions; returns the max value

tensor(6)

In [109]:
# What is the result and why?
t = torch.tensor([[1, 5, 3],
                 [4, 2, 6]])
torch.max(t, dim=0)

# Max values along the first axis

torch.return_types.max(
values=tensor([4, 5, 6]),
indices=tensor([1, 0, 1]))

In [110]:
# What is the result and why?
t = torch.tensor([[1, 5, 3],
                 [4, 2, 6]])
torch.max(t, dim=1)

# Max values along the second axis

torch.return_types.max(
values=tensor([5, 6]),
indices=tensor([1, 2]))

In [111]:
# What is the result and why?
t = torch.tensor([[1, 0, 0],
                 [4, 2, 6]], dtype=torch.float64)
torch.mean(t, dim=1)

# Mean value along the second axis

tensor([0.3333, 4.0000], dtype=torch.float64)

In [112]:
# What is the result and why?
t = torch.tensor([1, 0, 0])
torch.mean(t, dtype=torch.float)

# Mean value but the method has an aggressive type inference
# from the input tensor, thus integers end up as integers!!

tensor(0.3333)

In [113]:
# What is the result and why (incl. shape)?
x = torch.tensor([[1, 1, 1],
                 [1, 1, 1]])
torch.sum(x, dim=1, keepdim=True)

# sum along the second axis, but the dimensions are kept

tensor([[3],
        [3]])

In [114]:
# What is the result and why?
x = torch.tensor([[1, 2, 3],
                 [1, 1, 1]], dtype=torch.float64)
torch.linalg.vector_norm(x, ord=2, dim=1)

# length of the vector; distance from the origin to the point X
# [sqrt(14), sqrt(3)]

tensor([3.7417, 1.7321], dtype=torch.float64)

In [115]:
# What is the result and why?
x = torch.tensor([[1, 2, 3],
                 [1, 1, 1]], dtype=torch.float64)
torch.linalg.vector_norm(x, ord=2)

# length of the vector; distance from the origin to the point X
# No axis given!
# sqrt(17) -- it reduces all cells, so first all squared, summed
# up, and sqrted

tensor(4.1231, dtype=torch.float64)

In [116]:
# What is the output, shape, and dtype?
torch.tensor([1.0, 3.0]) // torch.tensor(2.0)

# Floor-division, with broadcasting

tensor([0., 1.])

In [117]:
# What is the output, shape, and dtype?
torch.tensor(5.0) // torch.tensor([2.0, 0.5])

# Floor-division, with broadcasting

tensor([ 2., 10.])

In [118]:
# What is the output, shape, and dtype?
torch.tensor([2.0, 3.0]) % torch.tensor([[2.0], [3.0]])

# Modulo, with broadcasting

tensor([[0., 1.],
        [2., 0.]])

In [119]:
# What is the output and why?
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch.ones_like(t)

# Tensor of the same shape and type filled
# with 1

tensor([[1, 1, 1],
        [1, 1, 1]])